### PR TITLE
Better debug

### PR DESCRIPTION
**Pull request by mjmeans**
I'm using an XIAO ESP32C6 and I am having an issue with ISO14443 being much slower than ISO15693 and wanted to better see what was happening. This slowness may actually be faulty module. But these updated macros are helping me trace the issue. I also want to extend ISO14443 to be able to read Type A NTAG 213 tag memory and these will help me do it.

### CODE REVIEW

**Comment by mjmeans** [comment]
Also, I've turned on Discussions on my fork. If you want to contact me to discuss this or other PR's, you can go there. Or you can turn on Discussions or Issues on your repo in Settings and ping me. I'll be actively working on implementing NTAG 213 memory reading and writing of ISO14443 tags this week.

**Comment by mjmeans** [comment]
I have some more debugging system changes to this and some fixes for ISO14443 that I'm testing. But I've made progress on ISO14443 NTAG 215 cards....

The function isCardPresent() calls readCardSerial() which calls activateTypeA() which calls loadRFConfig(0x0, 0x80) and then setRF_on() which has a 500 ms timeout if it fails. It fails if the RF is already on. On my machine with DEBUG enabled, the read performance for NTAG 215 card and its memory pages is about 1450 ms. In addition, the failed setRF_on() causes the function calling it to fail every other time it's called. So for example if your call to isCardPresent() succeeds, the subsequent call to readCardSerial() fails and you get no data from the card.

This can be mitigated by calling setRF_off() after setupRF() in setup() and then making sure to call setRF_off() after each call to isCardPresent() or readCardSerial() in loop(). When doing this on my machine it solves the issue with failing every other call and shortens the amount of time it takes to read the NTAG 215 card and its memory when DEBUG is enabled to ~935-950 ms.

Having to turn on and off the RF field is not efficient. It only takes about 13 ms to do so, but I don't think it should be necessary to cycle the RF field unless the board needs to be reset. The ISO15693 code only calls setRF_on() in setupRF() and I suspecct that this is how the ISO14443 code should work as well.

I think just removing the calls to loadRFConfig() and setRF_on() inside activateTypeA() will solve this without having to manually call setRF_off() at several times in user code. I'l be testing this theory tomorrow and hoppefully revising the PR when I've confirmed it works right.

**Comment by mjmeans** [comment]
This PR for better debug is ready to merge. I'm going to start a new branch focusing on fixing the performance issues in ISO14443.

**Comment by tueddy** [comment]
@mjmeans , first of all, thank you very much for your contribution!

When I see all your changes just for debugging I can't keep track of it at all! So I don't know yet if I can adopt it like this. For your debugging it may be ok but for this library it seems way too much!

About your problem: You sometimes have a big delay when reading a 14443 tag? I've had it too, usually when the RFID tag is almost out of reading range. A simple remedy is to apply real 5V to the 5V pin (this is the supply voltage of the RF part) and not just 3.3V. This increases the reading range and reliability. Otherwise, a loop that recognizes and reads over error detections also helps. Also remove any metal out of reader.

I can't say anything about the ESP32-C6 as I haven't tested it yet. But for a normal ESP-32 & S3 it seems to work well. For the newer models do you use Arduino IDE or pioarduino? Because the more modern ESP-IDF is used there. I have tested the library with Arduino 2.0.17/IDF 4.4 & 3.0.7/IDF 5.1 and the 14443 tags are recognized quite reliably!

Feel free to contribute further improvements, 
greetings Dirk

**Comment by mjmeans** [comment]
I provide the 5V from the USB bus, not form 3v3. The PN5180 is being supplied both actual 5V and 3V3. I'm using Arduino IDE 2.3.3.

For the XIAO-ESP32C6 board I make the following changes to PN5180-ISO14443.ino:

```
#define PN5180_NSS    SS    // D3    GPIO21  SS    SDIO_DATA1
#define PN5180_MOSI   MOSI  // D10   GPIO18  MOSI  SDIO_CMD
#define PN5180_MISO   MISO  // D9    GPIO20  MISO  SDIO_DATA0
#define PN5180_SCK    SCK   // D8    GPIO19  SCK   SDKIO_CLK
#define PN5180_BUSY   D4    // D4    GPIO22  SDA   SDIO_DATA2
#define PN5180_RST    D5    // D5    GPIO23  SCL   SDIO_DATA3
```

```
// XIAO-ESP32C6 requires FSPI
SPIClass PN5180_SPI(FSPI);
PN5180ISO14443 nfc(PN5180_NSS, PN5180_BUSY, PN5180_RST, PN5180_SPI);
```

```
  Serial.begin(115200);
  while (!Serial);

```
That's so I cn catch all the debug responses from the beginning.

For PN5180-Library files enable "`#define DEBUG 1` in PN5180.cpp, PN5180ISO14443.cpp, and Debug.h (since it has the formatHex() code in it). 

From the debug console:
```
==================================
Uploaded: Oct 29 2024 16:42:20
PN5180 ISO14443 Demo Sketch
| PN5180::begin(sck=-1, miso=-1, mosi=-1, ss=-1)
|  Default SPI pinout: SS=21, MOSI=18, MISO=20, SCK=19
----------------------------------
PN5180 Hard-Reset...
| PN5180::reset()
|  wait for system to start up (500 ms)
----------------------------------
Reading product version...
| PN5180::readEEprom(addr=10, *buffer, len=2)
|  Reading EEPROM at 0x10, size=2...
|  PN5180::transceiveCommand(*sendBuffer, sendBufferLen=3, *recvBuffer, recvBufferLen=2)
|   Sending SPI frame: '07 10 02'
|   Receiving SPI frame...
|   Received: '00 04'
|  EEPROM values: 00 04 
Product version=4.0
----------------------------------
Reading firmware version...
| PN5180::readEEprom(addr=12, *buffer, len=2)
|  Reading EEPROM at 0x12, size=2...
|  PN5180::transceiveCommand(*sendBuffer, sendBufferLen=3, *recvBuffer, recvBufferLen=2)
|   Sending SPI frame: '07 12 02'
|   Receiving SPI frame...
|   Received: '00 04'
|  EEPROM values: 00 04 
Firmware version=4.0
----------------------------------
Reading EEPROM version...
| PN5180::readEEprom(addr=14, *buffer, len=2)
|  Reading EEPROM at 0x14, size=2...
|  PN5180::transceiveCommand(*sendBuffer, sendBufferLen=3, *recvBuffer, recvBufferLen=2)
|   Sending SPI frame: '07 14 02'
|   Receiving SPI frame...
|   Received: '00 99'
|  EEPROM values: 00 99 
EEPROM version=153.0
----------------------------------
Reading firmware version...
| PN5180::readEEprom(addr=12, *buffer, len=2)
|  Reading EEPROM at 0x12, size=2...
|  PN5180::transceiveCommand(*sendBuffer, sendBufferLen=3, *recvBuffer, recvBufferLen=2)
|   Sending SPI frame: '07 12 02'
|   Receiving SPI frame...
|   Received: '00 04'
|  EEPROM values: 00 04 
Firmware version=4.0
----------------------------------
Reading EEPROM version...
| PN5180::readEEprom(addr=14, *buffer, len=2)
|  Reading EEPROM at 0x14, size=2...
|  PN5180::transceiveCommand(*sendBuffer, sendBufferLen=3, *recvBuffer, recvBufferLen=2)
|   Sending SPI frame: '07 14 02'
|   Receiving SPI frame...
|   Received: '00 99'
|  EEPROM values: 00 99 
EEPROM version=153.0
----------------------------------
Enable RF field...
| Loading RF-Configuration...
|  Load RF-Config: txConf=00, rxConf=80
|   PN5180::transceiveCommand(*sendBuffer, sendBufferLen=3, *recvBuffer, recvBufferLen=0)
|    Sending SPI frame: '11 00 80'
|  done.
|  Turning ON RF field...
|  Set RF ON
|   PN5180::transceiveCommand(*sendBuffer, sendBufferLen=2, *recvBuffer, recvBufferLen=0)
|    Sending SPI frame: '16 00'
|   wait for RF field to set up (max 500ms)
|   PN5180::clearIRQStatus(mask=00000200)
|    Clear IRQ-Status with mask
|    PN5180::writeRegister(reg=3, value=512)
|     Write Register 0x03, value (LSB first)=0x00020000
|     PN5180::transceiveCommand(*sendBuffer, sendBufferLen=6, *recvBuffer, recvBufferLen=0)
|      Sending SPI frame: '00 03 00 02 00 00'
|  done.
----------------------------------
Loop #0
| PN5180ISO14443::isCardPresent()
|  PN5180ISO14443::readCardSerial(*buffer)
|   PN5180ISO14443::activateTypeA(*buffer, kind=0)
|    Load RF-Config: txConf=00, rxConf=80
|     PN5180::transceiveCommand(*sendBuffer, sendBufferLen=3, *recvBuffer, recvBufferLen=0)
|      Sending SPI frame: '11 00 80'
|    Set RF ON
|     PN5180::transceiveCommand(*sendBuffer, sendBufferLen=2, *recvBuffer, recvBufferLen=0)
|      Sending SPI frame: '16 00'
|     wait for RF field to set up (max 500ms)
|     *** ERROR: Set RF ON timeout
```

This timeout is caused by the RF field already being on which means that the TX_RFON_IRQ_STAT bit in IRQ_STATUS register is never set and the 500 ms timeout happens. I also see later in the logs (not shown) a 200ms timeout tripped in PN5180ISO14443::activateTypeA() `timeout in PN5180_TS_WaitTransmit!`

This tells me it's taking 700 ms longer to read the tag than it should.

`PN5180ISO14443::activateTypeA()` directly calls `PN5180ISO14443::loadRFConfig()` and `PN5180::setRF_on()` which is the only thing that `PN5180ISO14443::setupRF()` does, the call to `nfc.setupRF()` is redundant at best. However, it leaves the RF field on which causes the 500 ms timeout.

Adding `nfc.setRF_off();` after `nfc.setupRF();` in `void setup()`, and before `if (!nfc.readCardSerial(uid))` in `void loop()` resolves the repeated 500 ms timeout and the 200 ms timeout, by allowing the IRQ_STATUS register to operate as expeccted. This reduces the typical time it takes to read a TypeA card with a 4-byte UID from approx. 800 ms to only 93 ms on average in my setup. 90% improvement in speed.

But manually calling `setRF_off()` in user code is a workaround. The library should gracefully handle this internally by checking to see if RF is already on and acting accordingly, like automatically cycling RF off and on when necessary.

Oh, and the above log clip is an example of how my new debug macros helps see the call stack that is in place without having to use a code debugger. Also, the new macros should not affect any legacy user code that relies on the simpler PN5180DEBUG(msg) macro. That still works as intended, except for putting the "| " in front of it.

**Comment by mjmeans** [comment]
I've turned on Issues and Discussions features on my fork of your repo. I've discovered some anomalies in the ISO15693 functionality when reading multiple tags simultaneously. Probably the collision detection algorithm is wrong.

**Comment by tueddy** [comment]
I maintain this library mainly for the [ESPuino ](https://github.com/biologist79/ESPuino)project, an RFID Kids player. E.g. [Here ](https://github.com/biologist79/ESPuino/blob/master/src/RfidPn5180.cpp)you can see the 14443/15696 detection loop. Even password protected tags can be unlocked & read. Collision detection does not play a role there. 

I don't plan to turn on the discussion here for now, but only record issues and take over PRs. Feel free to contribute further improvements, they are welcome!

P.S.: i have a lot of 15693 tags here so i could test anti collision..

**Comment by mjmeans** [comment]
I've added an Issue on my fork and invited the original author of PN5180ISO15693::getInventoryMultiple() to offer some insight.

I haven't played with password protected tags yet. I doubt I will need to. But I have played with reading their memory pages.

My goal with multiple tag reading is to be able to read an entire box or roll of tags at once. To be able to read an entire roll or box of 100 tags at once would be great! So far the maximum number of tags I've been able to read at one time on the PN5180 board is 10. But it's not reliable. 6 to 8 at once is reliable if they are flat tags all stacked on top of each other on top of the reader. I used the credit card / hotel room key sized tags. 3 or 4 tags can be reliably read at once about an inch away from the reader.

This is quite short compared to the ISO15693 and PN5180 theoretical capabilities which should be able to read NFC Type 5 tags up to 1.5m away, but realistically in an RF noisy non-ideal environment perhaps 700-800 mm away could be reliable. I'm hoping to achieve 300 mm range for single tag, or 80 mm range to read a box of tags at once.

I realize that the PN5180 board's antenna is far too small to provide a large or strong enough RF field to do what I want, and antenna design is, well, tricky. I have decades of experience in digital circuit designs but no experience if RF (yet). The NXP PN5180 chip is capable of handling it according to their docs. So, I have an official NXP 15693 front end dev kit on the way from Digikey. It has a larger pre-tuned antenna that I intend to try. That dev kit also has the ability to test and characterize custom antenna designs using NXPs software so that the 'gear' settings in the NXP chip can be set to work with larger antennas capable of projecting a larger RF field.

**Pull request merged**
