### PR TITLE
Remove line that overwrites AQTA with UID

### PR DESCRIPTION
**Pull request by bettse**
[Remove line that overwrites AQTA with UID](https://github.com/tueddy/PN5180-Library/pull/4/commits/1f07c05422af35e5cdba6c3281693c00d4356fb1)

### CODE REVIEW

**Comment by tueddy** [comment]
Hi Eric,

thank's for your PR! 
Can you explain what's your issue and fix exactly? Do you have steps to reproduce your problem?

**Comment by bettse** [comment]
So far as I can tell, this line sets the ATQA to the first two byte of the `buffer`: https://github.com/tueddy/PN5180-Library/pull/4/files#diff-5f7dcd31e5f622455c73ad27cb7bb1a6aa4d68c4cf32d475e8228789650e6365R142

Then the lines I'm removing overwrite those two bytes.  

Here is the project where I was experiencing this: https://gitlab.com/bettse/keypad_mitm/-/blob/main/src/main.ino#L488 but it is far more than just a reproduction of this problem.

**Comment by tueddy** [comment]
Hi @bettse,

I've tested the arduino example and it works with and without these lines from your PR, tested with my 4 Byte UID cards. 
But i'm unsure if this fix is valid.
Have you tested with a 4, 7 or 10 Byte UID? 
https://www.nxp.com/docs/en/application-note/AN10927.pdf

Please explain a bit more details about your issue.

Thank's
Dirk

**Comment by tueddy** [comment]
Closed due to inactivity. 
Feel free to open a new one if problem exists!

**Pull request closed without merging**
