### PR TITLE
Add code to allow authentication with Mifare Classic cards

### PR DESCRIPTION
**Pull request by golyalpha**
Just some code to allow for authentication with Mifare Classic cards.

"Unfortunately" has to live in the generic PN5180 as it's a reader command, not a card command.

It seems kind of slow. as trying out 5 invalid keys takes around 3s on the reader, including card halt and wake-up between attempts - the only way I could get the card to reliably respond to each attempt. But I suspect the only way to get around that would be to implement the authentication scheme in software (assuming such a thing is even possible with the PN5180).

(Also took the liberty of replacing tabs with spaces)

### CODE REVIEW

**Comment by tueddy** [comment]
@golyalpha, thank's for your PR!
Aren't Mifaire cards always ISO-14443? Then the method should be moved to PN5180ISO14443.cpp?
There already some mifaire commands available:
https://github.com/tueddy/PN5180-Library/blob/4a1f1399491ec452015389dc10c86a0505b2b9dd/PN5180ISO14443.h#L34

**Comment by golyalpha** [comment]
@tueddy Hey, yes, they are always ISO-14443, but MFC auth isn't part of it. The command is actually for the reader itself, rather than the card. This would mean either exposing the `transceiveCommand` method and PN5180_SPI from PN5180 publicly, or writing a wrapper method around it that would wrap the transceive call in an SPI transaction.

**Comment by tueddy** [comment]
For reference: 
MIFARE_AUTHENTICATE - 0x0C command is described on page 31 in  [PN5180A0XX_C3_C4.pdf](https://github.com/tueddy/PN5180-Library/blob/master/doc/PN5180A0XX-C3.pdf)

**Comment by tueddy** [comment]
Cannot test but command MIFARE_AUTHENTICATE looks right!
@golyalpha thanks for your contribution!

**Pull request merged**
